Find python binary for nbctl

diff --git a/roles/iri/files/nbctl b/roles/iri/files/nbctl
--- a/roles/iri/files/nbctl
+++ b/roles/iri/files/nbctl
@@ -1,4 +1,18 @@
-#!/usr/bin/env python
+#!/bin/sh
+
+# Find the python binary
+""":"
+
+for cmd in python3 python
+do
+   command -v > /dev/null $cmd && exec $cmd $0 "$@"
+done
+
+>&2 echo "Error: Python not found"
+
+exit 2
+
+":"""
 import argparse
 import tempfile
 import logging
